made changes to docker and pipeline files

diff --git a/.github/workflows/deploy-to-server.yml b/.github/workflows/deploy-to-server.yml
--- a/.github/workflows/deploy-to-server.yml
+++ b/.github/workflows/deploy-to-server.yml
@@ -15,45 +15,73 @@ jobs:
     deploy-to-server:
         runs-on: ubuntu-latest
         steps:
-            - name: checkout-code
-              uses: actions/checkout@v4
-            
-            - name: ssh to server and create a folder
-              uses: appleboy/ssh-action@v1
-              with:
+             - name: Deploy to instance
+               uses: appleboy/ssh-action@v1.0.3
+               with:
                 host: ${{secrets.EC2_SSH_HOST}}
                 username: ${{secrets.EC2_SSH_USER}}
                 key: ${{secrets.EC2_SSH_PRIVATE_KEY}}
                 script: |
-                  sudo apt update
-                  sudo apt-get install docker.io docker-compose-v2 -y
-                  sudo usermod -aG docker $USER && newgrp docker
-                  #echo "${sudo systemctl status docker}"
-                  echo " starting deployment"
-                  mkdir -p ~/devops    
-                  cd ~/devops
-                  echo "Welcome to server"
-            - name : Copy the docker-compose file
-              uses: appleboy/scp-action@v1
-              with:
-                host: ${{ secrets.EC2_SSH_HOST }}
-                username: ${{ secrets.EC2_SSH_USER }}
-                key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
-                source: docker-compose.yml
-                target: ~/devops
-            - name: SSH to Prod server and create app folder
-              uses: appleboy/ssh-action@v1.0.3
-              with:
-                host: ${{ secrets.EC2_SSH_HOST }}
-                username: ${{ secrets.EC2_SSH_USER }}
-                key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
-                script: |
-                   echo "running app"
-                   export DOCKERHUB_USER= ${{vars.DOCKERHUB_USER}}  
-                   export DOCKER_TAG= ${{github.sha}}
-                   echo "${{ vars.DOCKERHUB_USER }}"
-                   echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login  -u "${{ vars.DOCKERHUB_USER }}" --password-stdin
-                   cd ~/devops
-                   DOCKERHUB_USER=${{ vars.DOCKERHUB_USER }}
-                   docker compose up -d --build --force-recreate   
+                   echo "Updating system"
+                   sudo apt update -y
+                   if ! command -v docker &> /dev/null
+                   then
+                      echo " Docker not found ... installing"
+                      sudo apt install -y docker.io docker-compose-v2
+                      sudo usermod -aG docker $USER && newgrp docker
+                      sudo systemctl status docker
+                      sudo systemctl enable docker
+                    else
+                      echo "docker is already installed "
+                    fi
 
+                    echo "Verifing MySQL"
+                    if ! command -v mysql &> /dev/null
+                    then
+                        echo "MYSQL not found ... installing"
+                        sudo apt install mysql-server -y
+                        sudo systemctl start mysql
+                        sudo systemctl enable mysql
+                    else 
+                        echo "MYSQL already installed"
+                    fi
+
+                    echo " configuring MYSQL.."
+                    sudo systemctl start mysql
+
+                    sudo mysql -e "ALTER USER 'root'@'localhost' IDENTIFIED WITH mysql_native_password BY 'Test@123';FLUSH PRIVILEGES;"
+
+                    sudo mysql -u root -pTest@123 -e "CREATE DATABASE IF NOT EXISTS bankappdb;" || true
+
+                    echo "allow external connections"
+
+                    sudo sed -i "s/bind-address.*/bind-address = 0.0.0.0/" /etc/mysql/mysql.conf.d/mysqld.cnf
+                    
+                    sudo systemctl restart mysql
+
+                    echo " Docker login"
+                    echo "${{ secrets.DOCKERHUB_TOKEN}}" | docker login -u "${{ vars.DOCKERHUB_USER }}" --password-stdin
+                    
+                    echo "Stop old container..."
+                    docker stop bankapp || true
+                    docker rm bankapp || true
+
+                    echo "Pull latest image..."
+                    docker pull ${{ vars.DOCKERHUB_USER }}/ai-bankapp-devsecops:latest
+
+                    echo "Setting environment variables..."   
+
+                    export MYSQL_HOST=${{ secrets.MYSQL_HOST }}
+                    export MYSQL_PORT=3306
+                    export MYSQL_DATABASE=bankappdb
+                    export MYSQL_USER=${{ secrets.MYSQL_USER }}
+                    export MYSQL_PASSWORD=${{ secrets.MYSQL_PASSWORD }}
+
+                    echo "Run container..."
+                    docker run -d -p 8080:8080 --name bankapp \
+                      -e MYSQL_HOST=$MYSQL_HOST \
+                      -e MYSQL_PORT=$MYSQL_PORT \
+                      -e MYSQL_DATABASE=$MYSQL_DATABASE \
+                      -e MYSQL_USER=$MYSQL_USER \
+                      -e MYSQL_PASSWORD=$MYSQL_PASSWORD \
+                      ${{ vars.DOCKERHUB_USER }}/ai-bankapp-devsecops:latest
